name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  run_commands:
    runs-on: ubuntu-latest # Menjalankan di lingkungan Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update and upgrade system
        run: |
          sudo apt update -y
          sudo apt upgrade -y

      - name: Install nvm (Node Version Manager)
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source ~/.bashrc # reload bashrc supaya nvm bisa dipakai di session ini
          nvm install 18
          nvm use 18

      - name: Install npm dependencies
        run: |
          npm install

      - name: Start the application
        run: |
          npm start
